version: '3.8'

services:
  server:
    image: react-video-stream
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - ./app/src:/src
    networks:
      - mynetwork

networks:
  mynetwork: